/**
 * Stable domain invariant IDs.
 *
 * Catalog: docs/domain/invariants.md
 * Narrative: docs/architecture/domain-invariants.md
 *
 * Import these IDs in tests and comments. Do not invent a parallel list.
 */
export const DomainInvariant = {
  LISTING_EXCLUSIVE_RESERVE: "INV-LISTING-EXCLUSIVE-RESERVE",
  LISTING_SOLD_IRREVERSIBLE: "INV-LISTING-SOLD-IRREVERSIBLE",
  LISTING_RESERVATION_TTL: "INV-LISTING-RESERVATION-TTL",
  LISTING_CHECKOUT_CURRENCY: "INV-LISTING-CHECKOUT-CURRENCY",
  ORDER_TOTAL_COMPOSITION: "INV-ORDER-TOTAL-COMPOSITION",
  ORDER_ITEM_UNIQUE: "INV-ORDER-ITEM-UNIQUE",
  ORDER_PRICE_SNAPSHOT: "INV-ORDER-PRICE-SNAPSHOT",
  ORDER_ATOMIC_CREATE: "INV-ORDER-ATOMIC-CREATE",
  ORDER_IDEMPOTENCY: "INV-ORDER-IDEMPOTENCY",
  ORDER_STATUS_MACHINE: "INV-ORDER-STATUS-MACHINE",
  PAYMENT_TRUSTED_CONFIRM: "INV-PAYMENT-TRUSTED-CONFIRM",
  PAYMENT_WEBHOOK_AUTHENTIC: "INV-PAYMENT-WEBHOOK-AUTHENTIC",
  PAYMENT_WEBHOOK_IDEMPOTENT: "INV-PAYMENT-WEBHOOK-IDEMPOTENT",
  PAYMENT_LINK_IDEMPOTENT: "INV-PAYMENT-LINK-IDEMPOTENT",
  AUTH_OWNERSHIP: "INV-AUTH-OWNERSHIP",
  AUTH_REFRESH_FAMILY: "INV-AUTH-REFRESH-FAMILY",
  SELLER_COMMISSION_DECIMAL: "INV-SELLER-COMMISSION-DECIMAL",
  SELLER_TXN_UNIQUE: "INV-SELLER-TXN-UNIQUE",
  SELLER_LEDGER_SOURCE: "INV-SELLER-LEDGER-SOURCE",
  AUDIT_APPEND_ONLY: "INV-AUDIT-APPEND-ONLY",
  DB_ENUMS: "INV-DB-ENUMS",
} as const;

export type DomainInvariantId = (typeof DomainInvariant)[keyof typeof DomainInvariant];
